#!/usr/bin/env bash

set -e

dir=$(dirname "${BASH_SOURCE[0]}")

docker run --rm \
     -v $(pwd):/app \
     -v ~/.composer:/composer \
     fesor/composer install --ignore-platform-reqs --optimize-autoloader

export COMPOSE_FILE=docker-compose.yml:docker-compose.prod.yml
docker-compose build --force-rm
# Spooky bash hack for getting all images built by docker-compose
images=$(docker-compose config | grep -o 'image:.*' | cut -d" " -f2)
for image in $images; do
    echo "pushing image: $image"
    docker push $image
done
