#!/usr/bin/env bash

export $(cat ".env" | xargs)

database_container=$(docker-compose ps | grep "database" | cut -d" " -f 1)

docker exec -it $database_container sh -c " \
        exec psql --host=database \
            --port=5432 \
            --username=$DB_USER \
            --dbname=$DB_NAME \
            -1 -f /dumps/dump.sql \
    " && \
    echo "Successfully restored $table." || \
    echo "Error while restoring $table."
