#!/usr/bin/env bash

export $(cat ".env" | xargs)

container=$(docker-compose ps | grep "database" | cut -d" " -f 1)

docker exec -it $container sh -c "
    exec mysql -h database \
        -P 3306 \
        -u $DB_USER \
        -p$DB_PASS \
        $DB_NAME
"
