#!/usr/bin/env bash

export $(cat ".env" | xargs)

container=$(docker-compose ps | grep "database" | cut -d" " -f 1)

docker exec -it $container sh -c "
    PGPASSWORD=$DB_PASS psql --host database \
        --port=5432 \
        --username=$DB_USER \
        --dbname=$DB_NAME
"
